---
apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt
  namespace: megatron
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: hasiotis@gmail.com
    privateKeySecretRef:
      name: letsencrypt-secret
    http01: {}
